### ISSUE TITLE
Loading Errors

### ISSUE THREAD

**Issue by votexxd** [MrWalll/FairFight#4]
Everytime i try to load the lua i get tons of errors. I followed the Installation guide in your readme but i still get those errors.
Only a few other Luas i want to load have the same problem. Just tons of errors
![image](https://user-images.githubusercontent.com/74021218/179283584-39015728-d3bd-415c-89d4-17debad0ccf1.png)

**Comment by MrWalll** [comment]
You are missing the native file, Navigate to `Stand>Lua Scripts>Repository` and toggle `natives-1651208000` on

**Comment by votexxd** [comment]
I had all the Natives on. I turned them off and on again and then it worked. Thanks.
Also another thing. Could you add vehicles like the speedo, nightshark and more pvp vehicles to the blacklist? Would be amazing
